-- =============================================================================
-- normalized_data.xlsx 기반 레퍼런스 테이블 일괄 생성 스크립트
-- 테이블 이름은 엑셀 시트 이름의 대문자 버전과 일치합니다
-- =============================================================================

CREATE TABLE SITE (
    SITE_ID      VARCHAR2(10)  NOT NULL,
    SITE_NAME    VARCHAR2(100) NOT NULL,
    CREATED_AT   DATE          DEFAULT SYSDATE NOT NULL,
    UPDATED_AT   DATE          DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_SITE_TBL PRIMARY KEY (SITE_ID)
);

CREATE TABLE FACTORY (
    FACTORY_ID   VARCHAR2(20)  NOT NULL,
    FACTORY_NAME VARCHAR2(100) NOT NULL,
    SITE_ID      VARCHAR2(10)  NOT NULL,
    CREATED_AT   DATE          DEFAULT SYSDATE NOT NULL,
    UPDATED_AT   DATE          DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_FACTORY_TBL PRIMARY KEY (FACTORY_ID),
    CONSTRAINT FK_FACTORY_SITE_TBL FOREIGN KEY (SITE_ID) REFERENCES SITE(SITE_ID)
);

CREATE TABLE LINE (
    LINE_ID      VARCHAR2(30)  NOT NULL,
    LINE_NAME    VARCHAR2(100) NOT NULL,
    FACTORY_ID   VARCHAR2(20)  NOT NULL,
    CREATED_AT   DATE          DEFAULT SYSDATE NOT NULL,
    UPDATED_AT   DATE          DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_LINE_TBL PRIMARY KEY (LINE_ID),
    CONSTRAINT FK_LINE_FACTORY_TBL FOREIGN KEY (FACTORY_ID) REFERENCES FACTORY(FACTORY_ID)
);

CREATE TABLE PROCESS (
    PROCESS_ID    VARCHAR2(20)  NOT NULL,
    PROCESS_NAME  VARCHAR2(100) NOT NULL,
    PROCESS_ABBR  VARCHAR2(20),
    CREATED_AT    DATE          DEFAULT SYSDATE NOT NULL,
    UPDATED_AT    DATE          DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_PROCESS_TBL PRIMARY KEY (PROCESS_ID)
);

CREATE TABLE MODEL (
    MODEL_ID     VARCHAR2(50)  NOT NULL,
    MODEL_NAME   VARCHAR2(150) NOT NULL,
    PROCESS_ID   VARCHAR2(20)  NOT NULL,
    VENDOR       VARCHAR2(100),
    CREATED_AT   DATE          DEFAULT SYSDATE NOT NULL,
    UPDATED_AT   DATE          DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_MODEL_TBL PRIMARY KEY (MODEL_ID),
    CONSTRAINT FK_MODEL_PROCESS_TBL FOREIGN KEY (PROCESS_ID) REFERENCES PROCESS(PROCESS_ID)
);

CREATE TABLE EQUIPMENT (
    EQP_ID     VARCHAR2(50)  NOT NULL,
    EQP_NAME   VARCHAR2(150) NOT NULL,
    MODEL_ID   VARCHAR2(50)  NOT NULL,
    LINE_ID    VARCHAR2(30)  NOT NULL,
    CREATED_AT DATE          DEFAULT SYSDATE NOT NULL,
    UPDATED_AT DATE          DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_EQUIPMENT_TBL PRIMARY KEY (EQP_ID),
    CONSTRAINT FK_EQP_MODEL_TBL FOREIGN KEY (MODEL_ID) REFERENCES MODEL(MODEL_ID),
    CONSTRAINT FK_EQP_LINE_TBL FOREIGN KEY (LINE_ID) REFERENCES LINE(LINE_ID)
);

CREATE TABLE ERROR_CODE (
    ERROR_CODE   VARCHAR2(50)  NOT NULL,
    ERROR_DESC   VARCHAR2(200) NOT NULL,
    PROCESS_ID   VARCHAR2(20)  NOT NULL,
    CREATED_AT   DATE          DEFAULT SYSDATE NOT NULL,
    UPDATED_AT   DATE          DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_ERROR_CODE_TBL PRIMARY KEY (ERROR_CODE),
    CONSTRAINT FK_ERROR_PROCESS_TBL FOREIGN KEY (PROCESS_ID) REFERENCES PROCESS(PROCESS_ID)
);

CREATE TABLE STATUS (
    STATUS_ID    NUMBER(5)     NOT NULL,
    STATUS_NAME  VARCHAR2(50)  NOT NULL,
    CREATED_AT   DATE          DEFAULT SYSDATE NOT NULL,
    UPDATED_AT   DATE          DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_STATUS_TBL PRIMARY KEY (STATUS_ID)
);

CREATE TABLE DOWN_TYPE (
    DOWN_TYPE_ID   NUMBER(5)     NOT NULL,
    DOWN_TYPE_NAME VARCHAR2(50)  NOT NULL,
    CREATED_AT     DATE          DEFAULT SYSDATE NOT NULL,
    UPDATED_AT     DATE          DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_DOWN_TYPE_TBL PRIMARY KEY (DOWN_TYPE_ID)
);

