-- =============================================================================
-- FAB_TERMS_DICTIONARY 테이블 생성 스크립트
-- normalized_data.xlsx의 'fab_terms_dictionary' 시트 기반
-- 테이블 이름: FAB_TERMS_DICTIONARY (엑셀 시트 이름의 대문자 버전)
-- =============================================================================

CREATE TABLE FAB_TERMS_DICTIONARY (
    TERM_ID             VARCHAR2(32)    NOT NULL,
    TERM_EN             VARCHAR2(200)   NOT NULL,
    TERM_KOR_READING    VARCHAR2(200),
    MEANING_SHORT       VARCHAR2(500),
    MEANING_FIELD       CLOB,
    SEARCH_KEYWORDS     VARCHAR2(600),
    CREATED_AT          DATE            DEFAULT SYSDATE NOT NULL,
    UPDATED_AT          DATE            DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_FAB_TERMS_DICTIONARY PRIMARY KEY (TERM_ID)
);

COMMENT ON TABLE FAB_TERMS_DICTIONARY IS 'normalized_data.xlsx 기반 반도체 용어 사전';
COMMENT ON COLUMN FAB_TERMS_DICTIONARY.TERM_ID IS '원본 엑셀의 term_id (t_1 등)';
COMMENT ON COLUMN FAB_TERMS_DICTIONARY.TERM_EN IS '영문 용어';
COMMENT ON COLUMN FAB_TERMS_DICTIONARY.TERM_KOR_READING IS '한글 발음';
COMMENT ON COLUMN FAB_TERMS_DICTIONARY.MEANING_SHORT IS '요약 설명';
COMMENT ON COLUMN FAB_TERMS_DICTIONARY.MEANING_FIELD IS '상세 설명(필요 시 장문)';
COMMENT ON COLUMN FAB_TERMS_DICTIONARY.SEARCH_KEYWORDS IS '빠른 검색을 위한 소문자 키워드';

CREATE UNIQUE INDEX IDX_FAB_TERMS_TERM_EN ON FAB_TERMS_DICTIONARY (TERM_EN);
CREATE INDEX IDX_FAB_TERMS_TERM_KOR ON FAB_TERMS_DICTIONARY (TERM_KOR_READING);
CREATE INDEX IDX_FAB_TERMS_TERM_SEARCH ON FAB_TERMS_DICTIONARY (SEARCH_KEYWORDS);

CREATE OR REPLACE TRIGGER TRG_FAB_TERMS_DICTIONARY_UPD
BEFORE UPDATE ON FAB_TERMS_DICTIONARY
FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := SYSDATE;
END;
/


